# Spring Boot Application Configurations
spring.application.name=scm-backend
server.port=8080

# MySQL Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/scm_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# Hibernate JPA Settings for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Level
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.com.nexus.scm=DEBUG

# Gemini API setting
gemini.api.key=${GEMINI_API_KEY:MY_GEMINI_API_KEY}

# Ethereum Web3j Configurations (Ganache / Testnet)
ethereum.rpc.url=${ETHEREUM_RPC_URL:http://localhost:8545}
ethereum.private.key=${ETHEREUM_PRIVATE_KEY:0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d}
ethereum.contract.address=${ETHEREUM_CONTRACT_ADDRESS:0x1234567890123456789012345678901234567890}

